//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CommentsOfGames
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CommentsOfGames()
        {
            this.CommentsOfGames1 = new HashSet<CommentsOfGames>();
        }
    
        public int Id { get; set; }
        public string Topic { get; set; }
        public string Content { get; set; }
        public System.DateTime Date { get; set; }
        public int TargetGameId { get; set; }
        public int OwnerId { get; set; }
        public Nullable<int> ParentId { get; set; }
    
        public virtual Users Users { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CommentsOfGames> CommentsOfGames1 { get; set; }
        public virtual CommentsOfGames CommentsOfGames2 { get; set; }
        public virtual Games Games { get; set; }
    }
}
