//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CreatorsOfGames
    {
        public int Id { get; set; }
        public int GameId { get; set; }
        public int CreatorId { get; set; }
        public int CategoryId { get; set; }
    
        public virtual Creators Creators { get; set; }
        public virtual CreatorsCategories CreatorsCategories { get; set; }
        public virtual Games Games { get; set; }
    }
}
