//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Games
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Games()
        {
            this.AvarageGamesRating = new HashSet<AvarageGamesRating>();
            this.CommentsOfGames = new HashSet<CommentsOfGames>();
            this.IndividualGamesRating = new HashSet<IndividualGamesRating>();
            this.PhotosOfGames = new HashSet<PhotosOfGames>();
            this.CategoriesOfGames = new HashSet<CategoriesOfGames>();
            this.CreatorsOfGames = new HashSet<CreatorsOfGames>();
            this.GamesOfPublisher = new HashSet<GamesOfPublisher>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string OriginalName { get; set; }
        public int ProducentId { get; set; }
        public string NumberOfPlayers { get; set; }
        public string AgeRestrictions { get; set; }
        public string GameTime { get; set; }
        public string Description { get; set; }
        public int AvailableLevel { get; set; }
        public string Avatar { get; set; }
        public int PageCreatorId { get; set; }
        public string Website { get; set; }
        public string PremiereYear { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AvarageGamesRating> AvarageGamesRating { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CommentsOfGames> CommentsOfGames { get; set; }
        public virtual Users Users { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IndividualGamesRating> IndividualGamesRating { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PhotosOfGames> PhotosOfGames { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CategoriesOfGames> CategoriesOfGames { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CreatorsOfGames> CreatorsOfGames { get; set; }
        public virtual Publishers Publishers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GamesOfPublisher> GamesOfPublisher { get; set; }
    }
}
