//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BoardGamesDBEntities : DbContext
    {
        public BoardGamesDBEntities()
            : base("name=BoardGamesDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AvarageGamesRating> AvarageGamesRating { get; set; }
        public virtual DbSet<CommentsOfGames> CommentsOfGames { get; set; }
        public virtual DbSet<Games> Games { get; set; }
        public virtual DbSet<IndividualGamesRating> IndividualGamesRating { get; set; }
        public virtual DbSet<PhotosOfGames> PhotosOfGames { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<UsersPrivacyPolicy> UsersPrivacyPolicy { get; set; }
        public virtual DbSet<UsersPrivacyPolicyList> UsersPrivacyPolicyList { get; set; }
        public virtual DbSet<Categories> Categories { get; set; }
        public virtual DbSet<CategoriesOfGames> CategoriesOfGames { get; set; }
        public virtual DbSet<Creators> Creators { get; set; }
        public virtual DbSet<CreatorsCategories> CreatorsCategories { get; set; }
        public virtual DbSet<CreatorsOfGames> CreatorsOfGames { get; set; }
        public virtual DbSet<Friendship> Friendship { get; set; }
        public virtual DbSet<GamesOfPublisher> GamesOfPublisher { get; set; }
        public virtual DbSet<Publishers> Publishers { get; set; }
    }
}
